spring:
  mail:
    host: "smtp.office365.com"
    username: "notice@outlook.com.tw"
    password: "123456"
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          socketFactory:
            port: 578
            class: javax.net.ssl.SSLSocketFactory

logging:
  level:
    root: info

management:
  endpoints:
    web:
      exposure:
        include: "*"

notify:
  mail:
    from: "notice@outlook.com.tw"
    to: "admin001@notice.com.tw,admin002@outlook.com.tw"
    subject: "nexus-help schedule"

job-clean-nexus:
  cron: "0 0 21 * * 5"

nexus:
  url: "https://nexus.domain.com"
  username: "admin"
  password: "password"
  repository: "repositoryName"
  format: "docker"
  cleanup-policies:
  - policies-name: policiesRegularExpressionExclude
    field: name
    regex: "csnt/pinpoint-agent"
  - policies-name: policiesRegularExpressionExclude
    field: version
    regex: "[0-9]*[.][0-9]*[.][0-9]*[.]RELEASE"
  - policies-name: policiesRegularExpressionExclude
    field: version
    regex: "[0-9]*[.][0-9]*[.][0-9]*[.]RELEASE.DEV"
  - policies-name: policiesRegularExpressionExclude
    field: version
    regex: "[0-9]*[.][0-9]*[.][0-9]*[.]RELEASE.TEST"
  - policies-name: policiesRegularExpressionExclude
    field: version
    regex: "[0-9]*[.][0-9]*[.][0-9]*[.]RELEASE.UAT"
  - policies-name: policiesRegularExpressionExclude
    field: version
    regex: "[0-9]*[.][0-9]*[.][0-9]*[.]RELEASE.PROD"