version: 2
jobs:
  build:

    working_directory: ~/test-rest

    docker:
    - image: circleci/openjdk:8-jdk

    steps:

    - checkout

    - setup_remote_docker

    #      - restore_cache:
    #          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}
    #
    #      - run: mvn dependency:go-offline
    #
    #      - save_cache:
    #          paths:
    #            - ~/.m2
    #          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}

    - run: gradle build

    - store_test_results:
        path: target/surefire-reports

    - store_artifacts:
        path: build/libs/nexus-help-1.0.0.jar

    - run:
        name: build and push Docker image
        command: |
          TAG=1.0.$CIRCLE_BUILD_NUM
          docker build --build-arg PROJECT_NAME=nexus-help --build-arg PROJECT_VERSION=1.0.0 -t samchu/nexus-help:$TAG .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push samchu/nexus-help:$TAG